import { FormEvent, useState } from 'react'
import { auth } from '../services/api'
import { Icon } from './Icon'

export function AuthScreen({ onSuccess }: { onSuccess: () => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login'), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(false)
  async function submit(e: FormEvent) { e.preventDefault(); setError(''); setLoading(true); try { if (mode === 'register') await auth.register(email, password); await auth.login(email, password); onSuccess() } catch (err) { setError(err instanceof Error ? err.message : 'Что-то пошло не так') } finally { setLoading(false) } }
  return <main className="auth-page"><div className="auth-art" aria-hidden="true"><span className="eyebrow light">Университетская база знаний</span><h1>Знания,<br/>которые <em>бьются</em><br/>в одном ритме.</h1><p>Загружайте материалы и находите главное в сотнях страниц за несколько секунд.</p><div className="pulse-heart"><Icon name="heart" size={96}/><i/><i/><i/></div></div><section className="auth-card"><a className="brand dark" href="#"><Icon name="heart"/><span>знание</span></a><div className="auth-heading"><span className="section-index">01 / вход</span><h2>{mode === 'login' ? 'С возвращением' : 'Создайте аккаунт'}</h2><p>{mode === 'login' ? 'Продолжим искать важное.' : 'Один шаг до умного поиска.'}</p></div><form onSubmit={submit}><label>Почта<input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="student@university.ru" required autoComplete="email"/></label><label>Пароль<input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Не менее 8 символов" minLength={8} maxLength={128} required autoComplete={mode === 'login' ? 'current-password' : 'new-password'}/></label>{error && <div className="form-error">{error}</div>}<button className="primary wide" disabled={loading}>{loading ? 'Подождите…' : mode === 'login' ? 'Войти' : 'Зарегистрироваться'}<Icon name="arrow"/></button></form><button className="text-button" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError('') }}>{mode === 'login' ? 'Нет аккаунта? Создать' : 'Уже есть аккаунт? Войти'}</button></section></main>
}
